project_id = "uiuywvpwuwrsyowhotvz"

[functions.resident-register]
verify_jwt = false

[functions.resident-login]
verify_jwt = false

[functions.resident-qr-login]
verify_jwt = false

[functions.resident-qr-complaint]
verify_jwt = false
