-- Administrator-managed resident cards. The household master remains the
-- source for all 734 units; a card exists only when a resident needs details.

create table public.resident_cards (
  resident_id uuid primary key references public.profiles(id) on delete cascade,
  move_in_date date,
  memo text not null default '' check (char_length(memo) <= 2000),
  updated_by uuid references public.admin_accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.resident_card_fields (
  id bigint generated by default as identity primary key,
  resident_id uuid not null references public.resident_cards(resident_id) on delete cascade,
  label text not null check (char_length(label) between 1 and 50),
  value text not null default '' check (char_length(value) <= 500),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index resident_card_fields_resident_idx
on public.resident_card_fields(resident_id, sort_order, id);

create or replace function public.touch_resident_card()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  if tg_table_name = 'resident_cards' then
    new.updated_by = auth.uid();
  end if;
  return new;
end;
$$;

create trigger touch_resident_card
before insert or update on public.resident_cards
for each row execute function public.touch_resident_card();

create trigger touch_resident_card_field
before update on public.resident_card_fields
for each row execute function public.touch_resident_card();

alter table public.resident_cards enable row level security;
alter table public.resident_card_fields enable row level security;

create policy "admin resident cards read"
on public.resident_cards for select to authenticated
using (public.is_admin());

create policy "admin resident cards insert"
on public.resident_cards for insert to authenticated
with check (public.is_admin());

create policy "admin resident cards update"
on public.resident_cards for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "admin resident cards delete"
on public.resident_cards for delete to authenticated
using (public.is_admin());

create policy "admin resident card fields read"
on public.resident_card_fields for select to authenticated
using (public.is_admin());

create policy "admin resident card fields insert"
on public.resident_card_fields for insert to authenticated
with check (public.is_admin());

create policy "admin resident card fields update"
on public.resident_card_fields for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "admin resident card fields delete"
on public.resident_card_fields for delete to authenticated
using (public.is_admin());

revoke all on public.resident_cards, public.resident_card_fields from anon;
grant select, insert, update, delete on public.resident_cards, public.resident_card_fields to authenticated;
grant usage, select on all sequences in schema public to authenticated;

