-- 734 household master records and resident lifecycle.
-- Household-specific data must reference this master instead of accepting arbitrary building/unit values.

create table public.households (
  id bigint generated by default as identity primary key,
  building integer not null check (building between 101 and 107),
  unit integer not null check (unit between 101 and 9999),
  area_sqm numeric(6, 2) not null check (area_sqm > 0),
  current_resident_id uuid,
  created_at timestamptz not null default now(),
  unique (building, unit)
);

insert into public.households(building, unit, area_sqm) values
-- HOUSEHOLD_VALUES_BEGIN
  (101, 101, 74.93),
  (101, 102, 74.93),
  (101, 103, 74.93),
  (101, 104, 97.53),
  (101, 106, 74.93),
  (101, 107, 74.93),
  (101, 108, 100.34),
  (101, 201, 74.93),
  (101, 202, 74.93),
  (101, 203, 74.93),
  (101, 204, 97.53),
  (101, 206, 74.93),
  (101, 207, 74.93),
  (101, 208, 100.34),
  (101, 301, 74.93),
  (101, 302, 74.93),
  (101, 303, 74.93),
  (101, 304, 97.53),
  (101, 305, 74.93),
  (101, 306, 74.93),
  (101, 307, 74.93),
  (101, 308, 100.34),
  (101, 401, 74.93),
  (101, 402, 74.93),
  (101, 403, 74.93),
  (101, 404, 97.53),
  (101, 405, 74.93),
  (101, 406, 74.93),
  (101, 407, 74.93),
  (101, 408, 100.34),
  (101, 501, 74.93),
  (101, 502, 74.93),
  (101, 503, 74.93),
  (101, 504, 97.53),
  (101, 505, 74.93),
  (101, 506, 74.93),
  (101, 507, 74.93),
  (101, 508, 100.34),
  (101, 601, 74.93),
  (101, 602, 74.93),
  (101, 603, 74.93),
  (101, 604, 97.53),
  (101, 605, 74.93),
  (101, 606, 74.93),
  (101, 607, 74.93),
  (101, 608, 100.34),
  (101, 701, 74.93),
  (101, 702, 74.93),
  (101, 703, 74.93),
  (101, 704, 97.53),
  (101, 705, 74.93),
  (101, 706, 74.93),
  (101, 707, 74.93),
  (101, 708, 100.34),
  (101, 801, 74.93),
  (101, 802, 74.93),
  (101, 803, 74.93),
  (101, 804, 97.53),
  (101, 805, 74.93),
  (101, 806, 74.93),
  (101, 807, 74.93),
  (101, 808, 100.34),
  (101, 901, 74.93),
  (101, 902, 74.93),
  (101, 903, 74.93),
  (101, 904, 97.53),
  (101, 905, 74.93),
  (101, 906, 74.93),
  (101, 907, 74.93),
  (101, 908, 100.34),
  (101, 1001, 74.93),
  (101, 1002, 74.93),
  (101, 1003, 74.93),
  (101, 1004, 97.53),
  (101, 1005, 74.93),
  (101, 1006, 74.93),
  (101, 1007, 74.93),
  (101, 1008, 100.34),
  (101, 1101, 74.93),
  (101, 1102, 74.93),
  (101, 1103, 74.93),
  (101, 1104, 97.53),
  (101, 1105, 74.93),
  (101, 1106, 74.93),
  (101, 1107, 74.93),
  (101, 1108, 100.34),
  (101, 1201, 74.93),
  (101, 1202, 74.93),
  (101, 1203, 74.93),
  (101, 1204, 97.53),
  (101, 1205, 74.93),
  (101, 1206, 74.93),
  (101, 1207, 74.93),
  (101, 1208, 100.34),
  (101, 1301, 74.93),
  (101, 1302, 74.93),
  (101, 1303, 74.93),
  (101, 1304, 97.53),
  (101, 1305, 74.93),
  (101, 1306, 74.93),
  (101, 1307, 74.93),
  (101, 1308, 100.34),
  (101, 1401, 74.93),
  (101, 1402, 74.93),
  (101, 1403, 74.93),
  (101, 1404, 97.53),
  (101, 1405, 74.93),
  (101, 1406, 74.93),
  (101, 1407, 74.93),
  (101, 1408, 100.34),
  (101, 1501, 74.93),
  (101, 1502, 74.93),
  (101, 1503, 74.93),
  (101, 1504, 97.53),
  (101, 1505, 74.93),
  (101, 1506, 74.93),
  (101, 1507, 74.93),
  (101, 1508, 100.34),
  (101, 1601, 74.93),
  (101, 1602, 74.93),
  (101, 1603, 74.93),
  (101, 1604, 97.53),
  (101, 1605, 74.93),
  (101, 1606, 74.93),
  (101, 1607, 74.93),
  (101, 1608, 100.34),
  (101, 1701, 74.93),
  (101, 1702, 74.93),
  (101, 1703, 74.93),
  (101, 1704, 97.53),
  (101, 1705, 74.93),
  (101, 1706, 74.93),
  (101, 1707, 74.93),
  (101, 1708, 100.34),
  (101, 1801, 74.93),
  (101, 1802, 74.93),
  (101, 1803, 74.93),
  (101, 1804, 97.53),
  (101, 1805, 74.93),
  (101, 1806, 74.93),
  (101, 1807, 74.93),
  (101, 1808, 100.34),
  (101, 1901, 74.93),
  (101, 1902, 74.93),
  (101, 1903, 74.93),
  (101, 1904, 97.53),
  (101, 1905, 74.93),
  (101, 1906, 74.93),
  (101, 1907, 74.93),
  (101, 1908, 100.34),
  (101, 2001, 74.93),
  (101, 2002, 74.93),
  (101, 2003, 74.93),
  (101, 2004, 97.53),
  (101, 2005, 74.93),
  (101, 2006, 74.93),
  (101, 2007, 74.93),
  (101, 2008, 100.34),
  (101, 2105, 74.93),
  (101, 2106, 74.93),
  (101, 2107, 74.93),
  (101, 2108, 100.34),
  (102, 101, 100.34),
  (102, 102, 100.34),
  (102, 103, 100.34),
  (102, 104, 100.12),
  (102, 106, 129.34),
  (102, 107, 129.34),
  (102, 108, 129.34),
  (102, 201, 100.34),
  (102, 202, 100.34),
  (102, 203, 100.34),
  (102, 204, 100.12),
  (102, 206, 129.34),
  (102, 207, 129.34),
  (102, 208, 129.34),
  (102, 301, 100.34),
  (102, 302, 100.34),
  (102, 303, 100.34),
  (102, 304, 100.12),
  (102, 305, 99.91),
  (102, 306, 129.34),
  (102, 307, 129.34),
  (102, 308, 129.34),
  (102, 401, 100.34),
  (102, 402, 100.34),
  (102, 403, 100.34),
  (102, 404, 100.12),
  (102, 405, 99.91),
  (102, 406, 129.34),
  (102, 407, 129.34),
  (102, 408, 129.34),
  (102, 501, 100.34),
  (102, 502, 100.34),
  (102, 503, 100.34),
  (102, 504, 100.12),
  (102, 505, 99.91),
  (102, 506, 129.34),
  (102, 507, 129.34),
  (102, 508, 129.34),
  (102, 601, 100.34),
  (102, 602, 100.34),
  (102, 603, 100.34),
  (102, 604, 100.12),
  (102, 605, 99.91),
  (102, 606, 129.34),
  (102, 607, 129.34),
  (102, 608, 129.34),
  (102, 701, 100.34),
  (102, 702, 100.34),
  (102, 703, 100.34),
  (102, 704, 100.12),
  (102, 705, 99.91),
  (102, 706, 129.34),
  (102, 707, 129.34),
  (102, 708, 129.34),
  (102, 801, 100.34),
  (102, 802, 100.34),
  (102, 803, 100.34),
  (102, 804, 100.12),
  (102, 805, 99.91),
  (102, 806, 129.34),
  (102, 807, 129.34),
  (102, 808, 129.34),
  (102, 901, 100.34),
  (102, 902, 100.34),
  (102, 903, 100.34),
  (102, 904, 100.12),
  (102, 905, 99.91),
  (102, 906, 129.34),
  (102, 907, 129.34),
  (102, 908, 129.34),
  (102, 1001, 100.34),
  (102, 1002, 100.34),
  (102, 1003, 100.34),
  (102, 1004, 100.12),
  (102, 1005, 99.91),
  (102, 1006, 129.34),
  (102, 1007, 129.34),
  (102, 1008, 129.34),
  (102, 1101, 100.34),
  (102, 1102, 100.34),
  (102, 1103, 100.34),
  (102, 1104, 100.12),
  (102, 1105, 99.91),
  (102, 1106, 129.34),
  (102, 1107, 129.34),
  (102, 1108, 129.34),
  (102, 1201, 100.34),
  (102, 1202, 100.34),
  (102, 1203, 100.34),
  (102, 1204, 100.12),
  (102, 1205, 99.91),
  (102, 1206, 129.34),
  (102, 1207, 129.34),
  (102, 1208, 129.34),
  (102, 1301, 100.34),
  (102, 1302, 100.34),
  (102, 1303, 100.34),
  (102, 1304, 100.12),
  (102, 1305, 99.91),
  (102, 1306, 129.34),
  (102, 1307, 129.34),
  (102, 1308, 129.34),
  (102, 1401, 100.34),
  (102, 1402, 100.34),
  (102, 1403, 100.34),
  (102, 1404, 100.12),
  (102, 1405, 99.91),
  (102, 1406, 129.34),
  (102, 1407, 129.34),
  (102, 1408, 129.34),
  (102, 1501, 100.34),
  (102, 1502, 100.34),
  (102, 1503, 100.34),
  (102, 1504, 100.12),
  (102, 1505, 99.91),
  (102, 1506, 129.34),
  (102, 1507, 129.34),
  (102, 1508, 129.34),
  (102, 1601, 100.34),
  (102, 1602, 100.34),
  (102, 1603, 100.34),
  (102, 1604, 100.12),
  (102, 1605, 99.91),
  (102, 1606, 129.34),
  (102, 1607, 129.34),
  (102, 1608, 129.34),
  (102, 1701, 100.34),
  (102, 1702, 100.34),
  (102, 1703, 100.34),
  (102, 1704, 100.12),
  (102, 1705, 99.91),
  (102, 1706, 129.34),
  (102, 1707, 129.34),
  (102, 1708, 129.34),
  (102, 1801, 100.34),
  (102, 1802, 100.34),
  (102, 1803, 100.34),
  (102, 1804, 100.12),
  (102, 1903, 100.34),
  (102, 1904, 100.12),
  (103, 101, 74.93),
  (103, 102, 74.93),
  (103, 103, 74.93),
  (103, 104, 74.93),
  (103, 201, 74.93),
  (103, 202, 74.93),
  (103, 203, 74.93),
  (103, 204, 74.93),
  (103, 301, 74.93),
  (103, 302, 74.93),
  (103, 303, 74.93),
  (103, 304, 74.93),
  (103, 401, 74.93),
  (103, 402, 74.93),
  (103, 403, 74.93),
  (103, 404, 74.93),
  (103, 501, 74.93),
  (103, 502, 74.93),
  (103, 503, 74.93),
  (103, 504, 74.93),
  (103, 601, 74.93),
  (103, 602, 74.93),
  (103, 603, 74.93),
  (103, 604, 74.93),
  (103, 701, 74.93),
  (103, 702, 74.93),
  (103, 703, 74.93),
  (103, 704, 74.93),
  (103, 801, 74.93),
  (103, 802, 74.93),
  (103, 803, 74.93),
  (103, 804, 74.93),
  (103, 901, 74.93),
  (103, 902, 74.93),
  (103, 903, 74.93),
  (103, 904, 74.93),
  (103, 1001, 74.93),
  (103, 1002, 74.93),
  (103, 1003, 74.93),
  (103, 1004, 74.93),
  (103, 1101, 74.93),
  (103, 1102, 74.93),
  (103, 1103, 74.93),
  (103, 1104, 74.93),
  (103, 1201, 74.93),
  (103, 1202, 74.93),
  (103, 1203, 74.93),
  (103, 1204, 74.93),
  (103, 1301, 74.93),
  (103, 1302, 74.93),
  (103, 1303, 74.93),
  (103, 1304, 74.93),
  (103, 1401, 74.93),
  (103, 1402, 74.93),
  (103, 1403, 74.93),
  (103, 1404, 74.93),
  (103, 1501, 74.93),
  (103, 1502, 74.93),
  (103, 1503, 74.93),
  (103, 1504, 74.93),
  (103, 1601, 74.93),
  (103, 1602, 74.93),
  (103, 1603, 74.93),
  (103, 1604, 74.93),
  (103, 1701, 74.93),
  (103, 1702, 74.93),
  (103, 1703, 74.93),
  (103, 1704, 74.93),
  (103, 1801, 74.93),
  (103, 1802, 74.93),
  (103, 1803, 74.93),
  (103, 1804, 74.93),
  (103, 1903, 74.93),
  (103, 1904, 74.93),
  (103, 2003, 74.93),
  (103, 2004, 74.93),
  (103, 2103, 74.93),
  (103, 2104, 74.93),
  (104, 101, 129.34),
  (104, 102, 129.34),
  (104, 103, 100.17),
  (104, 104, 100.34),
  (104, 201, 129.34),
  (104, 202, 129.34),
  (104, 203, 100.17),
  (104, 204, 100.34),
  (104, 301, 129.34),
  (104, 302, 129.34),
  (104, 303, 100.17),
  (104, 304, 100.34),
  (104, 401, 129.34),
  (104, 402, 129.34),
  (104, 403, 100.17),
  (104, 404, 100.34),
  (104, 501, 129.34),
  (104, 502, 129.34),
  (104, 503, 100.17),
  (104, 504, 100.34),
  (104, 601, 129.34),
  (104, 602, 129.34),
  (104, 603, 100.17),
  (104, 604, 100.34),
  (104, 701, 129.34),
  (104, 702, 129.34),
  (104, 703, 100.17),
  (104, 704, 100.34),
  (104, 801, 129.34),
  (104, 802, 129.34),
  (104, 803, 100.17),
  (104, 804, 100.34),
  (104, 901, 129.34),
  (104, 902, 129.34),
  (104, 903, 100.17),
  (104, 904, 100.34),
  (104, 1001, 129.34),
  (104, 1002, 129.34),
  (104, 1003, 100.17),
  (104, 1004, 100.34),
  (104, 1101, 129.34),
  (104, 1102, 129.34),
  (104, 1103, 100.17),
  (104, 1104, 100.34),
  (104, 1201, 129.34),
  (104, 1202, 129.34),
  (104, 1203, 100.17),
  (104, 1204, 100.34),
  (104, 1301, 129.34),
  (104, 1302, 129.34),
  (104, 1303, 100.17),
  (104, 1304, 100.34),
  (104, 1401, 129.34),
  (104, 1402, 129.34),
  (104, 1403, 100.17),
  (104, 1404, 100.34),
  (104, 1501, 129.34),
  (104, 1502, 129.34),
  (104, 1503, 100.17),
  (104, 1504, 100.34),
  (104, 1601, 129.34),
  (104, 1602, 129.34),
  (104, 1603, 100.17),
  (104, 1604, 100.34),
  (104, 1703, 100.17),
  (104, 1704, 100.34),
  (105, 101, 100.34),
  (105, 102, 100.34),
  (105, 103, 74.93),
  (105, 104, 74.93),
  (105, 201, 100.34),
  (105, 202, 100.34),
  (105, 203, 74.93),
  (105, 204, 74.93),
  (105, 301, 100.34),
  (105, 302, 100.34),
  (105, 303, 74.93),
  (105, 304, 74.93),
  (105, 401, 100.34),
  (105, 402, 100.34),
  (105, 403, 74.93),
  (105, 404, 74.93),
  (105, 501, 100.34),
  (105, 502, 100.34),
  (105, 503, 74.93),
  (105, 504, 74.93),
  (105, 601, 100.34),
  (105, 602, 100.34),
  (105, 603, 74.93),
  (105, 604, 74.93),
  (105, 701, 100.34),
  (105, 702, 100.34),
  (105, 703, 74.93),
  (105, 704, 74.93),
  (105, 801, 100.34),
  (105, 802, 100.34),
  (105, 803, 74.93),
  (105, 804, 74.93),
  (105, 901, 100.34),
  (105, 902, 100.34),
  (105, 903, 74.93),
  (105, 904, 74.93),
  (105, 1001, 100.34),
  (105, 1002, 100.34),
  (105, 1003, 74.93),
  (105, 1004, 74.93),
  (105, 1101, 100.34),
  (105, 1102, 100.34),
  (105, 1103, 74.93),
  (105, 1104, 74.93),
  (105, 1201, 100.34),
  (105, 1202, 100.34),
  (105, 1203, 74.93),
  (105, 1204, 74.93),
  (105, 1301, 100.34),
  (105, 1302, 100.34),
  (105, 1303, 74.93),
  (105, 1304, 74.93),
  (105, 1401, 100.34),
  (105, 1402, 100.34),
  (105, 1403, 74.93),
  (105, 1404, 74.93),
  (105, 1501, 100.34),
  (105, 1502, 100.34),
  (105, 1503, 74.93),
  (105, 1504, 74.93),
  (105, 1601, 100.34),
  (105, 1602, 100.34),
  (105, 1603, 74.93),
  (105, 1604, 74.93),
  (105, 1703, 74.93),
  (105, 1704, 74.93),
  (105, 1803, 74.93),
  (105, 1804, 74.93),
  (106, 101, 100.34),
  (106, 102, 100.34),
  (106, 103, 74.93),
  (106, 104, 74.93),
  (106, 105, 74.93),
  (106, 106, 74.93),
  (106, 201, 100.34),
  (106, 202, 100.34),
  (106, 203, 74.93),
  (106, 204, 74.93),
  (106, 205, 74.93),
  (106, 206, 74.93),
  (106, 301, 100.34),
  (106, 302, 100.34),
  (106, 303, 74.93),
  (106, 304, 74.93),
  (106, 305, 74.93),
  (106, 306, 74.93),
  (106, 401, 100.34),
  (106, 402, 100.34),
  (106, 403, 74.93),
  (106, 404, 74.93),
  (106, 405, 74.93),
  (106, 406, 74.93),
  (106, 501, 100.34),
  (106, 502, 100.34),
  (106, 503, 74.93),
  (106, 504, 74.93),
  (106, 505, 74.93),
  (106, 506, 74.93),
  (106, 601, 100.34),
  (106, 602, 100.34),
  (106, 603, 74.93),
  (106, 604, 74.93),
  (106, 605, 74.93),
  (106, 606, 74.93),
  (106, 701, 100.34),
  (106, 702, 100.34),
  (106, 703, 74.93),
  (106, 704, 74.93),
  (106, 705, 74.93),
  (106, 706, 74.93),
  (106, 801, 100.34),
  (106, 802, 100.34),
  (106, 803, 74.93),
  (106, 804, 74.93),
  (106, 805, 74.93),
  (106, 806, 74.93),
  (106, 901, 100.34),
  (106, 902, 100.34),
  (106, 903, 74.93),
  (106, 904, 74.93),
  (106, 905, 74.93),
  (106, 906, 74.93),
  (106, 1001, 100.34),
  (106, 1002, 100.34),
  (106, 1003, 74.93),
  (106, 1004, 74.93),
  (106, 1005, 74.93),
  (106, 1006, 74.93),
  (106, 1101, 100.34),
  (106, 1102, 100.34),
  (106, 1103, 74.93),
  (106, 1104, 74.93),
  (106, 1105, 74.93),
  (106, 1106, 74.93),
  (106, 1201, 100.34),
  (106, 1202, 100.34),
  (106, 1203, 74.93),
  (106, 1204, 74.93),
  (106, 1205, 74.93),
  (106, 1206, 74.93),
  (106, 1301, 100.34),
  (106, 1302, 100.34),
  (106, 1303, 74.93),
  (106, 1304, 74.93),
  (106, 1305, 74.93),
  (106, 1306, 74.93),
  (106, 1401, 100.34),
  (106, 1402, 100.34),
  (106, 1403, 74.93),
  (106, 1404, 74.93),
  (106, 1405, 74.93),
  (106, 1406, 74.93),
  (106, 1501, 100.34),
  (106, 1502, 100.34),
  (106, 1503, 74.93),
  (106, 1504, 74.93),
  (106, 1505, 74.93),
  (106, 1506, 74.93),
  (106, 1601, 100.34),
  (106, 1602, 100.34),
  (106, 1603, 74.93),
  (106, 1604, 74.93),
  (106, 1605, 74.93),
  (106, 1606, 74.93),
  (106, 1701, 100.34),
  (106, 1702, 100.34),
  (106, 1703, 74.93),
  (106, 1704, 74.93),
  (106, 1705, 74.93),
  (106, 1706, 74.93),
  (106, 1801, 100.34),
  (106, 1802, 100.34),
  (106, 1803, 74.93),
  (106, 1804, 74.93),
  (106, 1805, 74.93),
  (106, 1806, 74.93),
  (106, 1901, 100.34),
  (106, 1902, 100.34),
  (106, 1903, 74.93),
  (106, 1904, 74.93),
  (106, 2001, 100.34),
  (106, 2002, 100.34),
  (107, 101, 74.93),
  (107, 102, 74.93),
  (107, 103, 74.93),
  (107, 104, 74.93),
  (107, 105, 74.93),
  (107, 106, 74.93),
  (107, 201, 74.93),
  (107, 202, 74.93),
  (107, 203, 74.93),
  (107, 204, 74.93),
  (107, 205, 74.93),
  (107, 206, 74.93),
  (107, 301, 74.93),
  (107, 302, 74.93),
  (107, 303, 74.93),
  (107, 304, 74.93),
  (107, 305, 74.93),
  (107, 306, 74.93),
  (107, 401, 74.93),
  (107, 402, 74.93),
  (107, 403, 74.93),
  (107, 404, 74.93),
  (107, 405, 74.93),
  (107, 406, 74.93),
  (107, 501, 74.93),
  (107, 502, 74.93),
  (107, 503, 74.93),
  (107, 504, 74.93),
  (107, 505, 74.93),
  (107, 506, 74.93),
  (107, 601, 74.93),
  (107, 602, 74.93),
  (107, 603, 74.93),
  (107, 604, 74.93),
  (107, 605, 74.93),
  (107, 606, 74.93),
  (107, 701, 74.93),
  (107, 702, 74.93),
  (107, 703, 74.93),
  (107, 704, 74.93),
  (107, 705, 74.93),
  (107, 706, 74.93),
  (107, 801, 74.93),
  (107, 802, 74.93),
  (107, 803, 74.93),
  (107, 804, 74.93),
  (107, 805, 74.93),
  (107, 806, 74.93),
  (107, 901, 74.93),
  (107, 902, 74.93),
  (107, 903, 74.93),
  (107, 904, 74.93),
  (107, 905, 74.93),
  (107, 906, 74.93),
  (107, 1001, 74.93),
  (107, 1002, 74.93),
  (107, 1003, 74.93),
  (107, 1004, 74.93),
  (107, 1005, 74.93),
  (107, 1006, 74.93),
  (107, 1101, 74.93),
  (107, 1102, 74.93),
  (107, 1103, 74.93),
  (107, 1104, 74.93),
  (107, 1105, 74.93),
  (107, 1106, 74.93),
  (107, 1201, 74.93),
  (107, 1202, 74.93),
  (107, 1203, 74.93),
  (107, 1204, 74.93),
  (107, 1205, 74.93),
  (107, 1206, 74.93),
  (107, 1301, 74.93),
  (107, 1302, 74.93),
  (107, 1303, 74.93),
  (107, 1304, 74.93),
  (107, 1305, 74.93),
  (107, 1306, 74.93),
  (107, 1401, 74.93),
  (107, 1402, 74.93),
  (107, 1403, 74.93),
  (107, 1404, 74.93),
  (107, 1405, 74.93),
  (107, 1406, 74.93),
  (107, 1501, 74.93),
  (107, 1502, 74.93),
  (107, 1503, 74.93),
  (107, 1504, 74.93),
  (107, 1505, 74.93),
  (107, 1506, 74.93),
  (107, 1601, 74.93),
  (107, 1602, 74.93),
  (107, 1603, 74.93),
  (107, 1604, 74.93),
  (107, 1605, 74.93),
  (107, 1606, 74.93),
  (107, 1701, 74.93),
  (107, 1702, 74.93),
  (107, 1703, 74.93),
  (107, 1704, 74.93),
  (107, 1705, 74.93),
  (107, 1706, 74.93),
  (107, 1801, 74.93),
  (107, 1802, 74.93),
  (107, 1803, 74.93),
  (107, 1804, 74.93)
-- HOUSEHOLD_VALUES_END
on conflict (building, unit) do update set area_sqm = excluded.area_sqm;

do $$
begin
  if (select count(*) from public.households) <> 734 then
    raise exception '세대 마스터는 정확히 734세대여야 합니다.';
  end if;
end;
$$;

alter table public.profiles drop constraint if exists profiles_building_unit_key;
alter table public.profiles drop constraint if exists profiles_phone_key;
alter table public.profiles add column household_id bigint references public.households(id) on delete restrict;
alter table public.profiles add column phone_last4 text;
alter table public.profiles add column membership_status text not null default 'pending'
  check (membership_status in ('pending', 'active', 'replaced', 'rejected'));
alter table public.profiles add column replaced_at timestamptz;

update public.profiles p
set household_id = h.id,
    phone_last4 = right(regexp_replace(p.phone, '[^0-9]', '', 'g'), 4),
    membership_status = case when p.approved then 'active' else 'pending' end
from public.households h
where h.building::text = p.building and h.unit::text = p.unit;

do $$
begin
  if exists(select 1 from public.profiles where household_id is null) then
    raise exception '세대 마스터에 없는 기존 회원의 동·호수가 있습니다. profiles를 먼저 정정해 주세요.';
  end if;
end;
$$;

alter table public.profiles alter column household_id set not null;
alter table public.profiles alter column phone_last4 set not null;
alter table public.profiles add constraint profiles_phone_last4_format check (phone_last4 ~ '^[0-9]{4}$');
create index profiles_household_idx on public.profiles(household_id);
create index profiles_active_household_idx on public.profiles(household_id) where membership_status = 'active';

alter table public.households
  add constraint households_current_resident_fk
  foreign key (current_resident_id) references public.profiles(id) on delete set null;

update public.households h
set current_resident_id = p.id
from public.profiles p
where p.household_id = h.id and p.approved = true and p.membership_status = 'active';

create table public.registration_requests (
  id bigint generated by default as identity primary key,
  applicant_id uuid not null unique references public.profiles(id) on delete cascade,
  household_id bigint not null references public.households(id) on delete restrict,
  phone text not null check (phone ~ '^01[016789][0-9]{7,8}$'),
  phone_last4 text not null check (phone_last4 ~ '^[0-9]{4}$'),
  request_type text not null check (request_type in ('new', 'replacement')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  previous_resident_id uuid references public.profiles(id) on delete set null,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index registration_requests_status_idx on public.registration_requests(status, created_at);
create index registration_requests_household_idx on public.registration_requests(household_id, status);

create table public.resident_auth_attempts (
  id bigint generated by default as identity primary key,
  attempt_type text not null check (attempt_type in ('register', 'login')),
  ip_hash text not null,
  created_at timestamptz not null default now()
);
create index resident_auth_attempts_limit_idx on public.resident_auth_attempts(attempt_type, ip_hash, created_at desc);

insert into public.registration_requests(applicant_id, household_id, phone, phone_last4, request_type, previous_resident_id)
select p.id,
       p.household_id,
       regexp_replace(p.phone, '[^0-9]', '', 'g'),
       p.phone_last4,
       case when h.current_resident_id is null then 'new' else 'replacement' end,
       h.current_resident_id
from public.profiles p
join public.households h on h.id = p.household_id
where p.approved = false
on conflict (applicant_id) do nothing;

alter table public.complaints add column household_id bigint references public.households(id) on delete restrict;
update public.complaints c
set household_id = p.household_id
from public.profiles p
where p.id = c.author_id;
alter table public.complaints alter column household_id set not null;
create index complaints_household_idx on public.complaints(household_id, created_at desc);

create or replace function public.set_complaint_household()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select household_id into new.household_id
  from public.profiles
  where id = new.author_id;

  if new.household_id is null then
    raise exception '세대가 확인되지 않는 회원입니다.';
  end if;

  return new;
end;
$$;
create trigger set_complaint_household
before insert or update of author_id on public.complaints
for each row execute function public.set_complaint_household();

create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles
    where id = auth.uid()
      and approved = true
      and membership_status = 'active'
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and approved = true
      and membership_status = 'active'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_household public.households%rowtype;
  phone_number text;
  last4 text;
begin
  phone_number := regexp_replace(coalesce(new.raw_user_meta_data->>'phone', ''), '[^0-9]', '', 'g');
  last4 := new.raw_user_meta_data->>'phone_last4';

  if phone_number !~ '^01[016789][0-9]{7,8}$' then
    raise exception '전화번호가 올바르지 않습니다.';
  end if;

  if last4 is null or last4 !~ '^[0-9]{4}$' then
    raise exception '전화번호 뒤 4자리가 올바르지 않습니다.';
  end if;

  select * into target_household
  from public.households
  where building = (new.raw_user_meta_data->>'building')::integer
    and unit = (new.raw_user_meta_data->>'unit')::integer;

  if not found then
    raise exception '등록되지 않은 세대입니다.';
  end if;

  insert into public.profiles(
    id, email, name, phone, building, unit,
    household_id, phone_last4, membership_status
  ) values (
    new.id,
    new.email,
    target_household.building || '동 ' || target_household.unit || '호 입주민',
    phone_number,
    target_household.building::text,
    target_household.unit::text,
    target_household.id,
    last4,
    'pending'
  );

  insert into public.registration_requests(
    applicant_id, household_id, phone, phone_last4, request_type, previous_resident_id
  ) values (
    new.id,
    target_household.id,
    phone_number,
    last4,
    case when target_household.current_resident_id is null then 'new' else 'replacement' end,
    target_household.current_resident_id
  );

  return new;
end;
$$;

create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if session_user <> 'postgres'
     and not public.is_admin()
     and (
       new.role <> old.role
       or new.approved <> old.approved
       or new.id <> old.id
       or new.email <> old.email
       or new.phone <> old.phone
       or new.building <> old.building
       or new.unit <> old.unit
       or new.household_id <> old.household_id
       or new.phone_last4 <> old.phone_last4
       or new.membership_status <> old.membership_status
     ) then
    raise exception '권한 및 입주 정보 필드는 변경할 수 없습니다.';
  end if;

  return new;
end;
$$;

create or replace function public.approve_registration(request_id bigint)
returns table(approved_household_id bigint, resident_replaced boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_request public.registration_requests%rowtype;
  target_household public.households%rowtype;
  old_resident_id uuid;
begin
  if not public.is_admin() then
    raise exception '관리자만 가입을 승인할 수 있습니다.';
  end if;

  select * into target_request
  from public.registration_requests
  where id = request_id
  for update;

  if not found or target_request.status <> 'pending' then
    raise exception '처리할 수 없는 가입 요청입니다.';
  end if;

  select * into target_household
  from public.households
  where id = target_request.household_id
  for update;

  old_resident_id := target_household.current_resident_id;

  update public.profiles
  set approved = true,
      membership_status = 'active',
      replaced_at = null
  where id = target_request.applicant_id;

  if old_resident_id is not null and old_resident_id <> target_request.applicant_id then
    update public.profiles
    set approved = false,
        membership_status = 'replaced',
        replaced_at = now()
    where id = old_resident_id;
  end if;

  update public.households
  set current_resident_id = target_request.applicant_id
  where id = target_request.household_id;

  update public.registration_requests
  set status = 'approved',
      request_type = case when old_resident_id is null then 'new' else 'replacement' end,
      previous_resident_id = old_resident_id,
      reviewed_by = auth.uid(),
      reviewed_at = now()
  where id = target_request.id;

  update public.registration_requests
  set request_type = 'replacement',
      previous_resident_id = target_request.applicant_id
  where household_id = target_request.household_id
    and status = 'pending'
    and id <> target_request.id;

  return query select target_request.household_id, old_resident_id is not null;
end;
$$;

create or replace function public.reject_registration(request_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_applicant_id uuid;
begin
  if not public.is_admin() then
    raise exception '관리자만 가입을 거절할 수 있습니다.';
  end if;

  update public.registration_requests
  set status = 'rejected', reviewed_by = auth.uid(), reviewed_at = now()
  where id = request_id and status = 'pending'
  returning applicant_id into target_applicant_id;

  if target_applicant_id is null then
    raise exception '처리할 수 없는 가입 요청입니다.';
  end if;

  update public.profiles
  set approved = false, membership_status = 'rejected'
  where id = target_applicant_id;
end;
$$;

create or replace function public.bootstrap_first_admin(
  target_building integer,
  target_unit integer,
  target_phone_last4 text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_request public.registration_requests%rowtype;
begin
  if session_user <> 'postgres' then
    raise exception 'SQL Editor의 postgres 역할에서만 실행할 수 있습니다.';
  end if;

  if exists(select 1 from public.profiles where role = 'admin' and approved = true and membership_status = 'active') then
    raise exception '이미 활성 관리자가 존재합니다.';
  end if;

  select r.* into target_request
  from public.registration_requests r
  join public.households h on h.id = r.household_id
  where h.building = target_building
    and h.unit = target_unit
    and r.phone_last4 = target_phone_last4
    and r.status = 'pending'
  order by r.created_at desc
  limit 1
  for update of r;

  if not found then
    raise exception '일치하는 가입 요청이 없습니다.';
  end if;

  update public.profiles
  set role = 'admin', approved = true, membership_status = 'active', replaced_at = null
  where id = target_request.applicant_id;

  update public.households
  set current_resident_id = target_request.applicant_id
  where id = target_request.household_id;

  update public.registration_requests
  set status = 'approved', reviewed_at = now()
  where id = target_request.id;

  return target_request.applicant_id;
end;
$$;

create or replace view public.profile_directory as
  select id, name, building, unit, role, approved, created_at
  from public.profiles
  where approved = true and membership_status = 'active';

alter table public.households enable row level security;
alter table public.registration_requests enable row level security;
alter table public.resident_auth_attempts enable row level security;

drop policy if exists "own or admin profiles read" on public.profiles;
drop policy if exists "own profile update" on public.profiles;
drop policy if exists "admin profiles update" on public.profiles;
create policy "own or admin profiles read" on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_admin());
create policy "admin profiles update" on public.profiles for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "complaints read" on public.complaints;
drop policy if exists "complaints insert" on public.complaints;
drop policy if exists "admin complaints update" on public.complaints;
create policy "complaints read" on public.complaints for select to authenticated
  using (public.is_active_user() and (author_id = auth.uid() or public.is_admin()));
create policy "complaints insert" on public.complaints for insert to authenticated
  with check (public.is_active_user() and ((author_id = auth.uid() and status = 'pending') or public.is_admin()));
create policy "admin complaints update" on public.complaints for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "comments read" on public.complaint_comments;
drop policy if exists "comments insert" on public.complaint_comments;
create policy "comments read" on public.complaint_comments for select to authenticated
  using (public.is_active_user() and exists(
    select 1 from public.complaints c
    where c.id = complaint_id and (c.author_id = auth.uid() or public.is_admin())
  ));
create policy "comments insert" on public.complaint_comments for insert to authenticated
  with check (public.is_active_user() and user_id = auth.uid() and exists(
    select 1 from public.complaints c
    where c.id = complaint_id and (c.author_id = auth.uid() or public.is_admin())
  ));

drop policy if exists "history read" on public.complaint_history;
create policy "history read" on public.complaint_history for select to authenticated
  using (public.is_active_user() and exists(
    select 1 from public.complaints c
    where c.id = complaint_id and (c.author_id = auth.uid() or public.is_admin())
  ));

drop policy if exists "notices read" on public.notices;
create policy "notices read" on public.notices for select to authenticated using (public.is_active_user());
drop policy if exists "monthly records read" on public.monthly_records;
create policy "monthly records read" on public.monthly_records for select to authenticated using (public.is_active_user());
drop policy if exists "monthly items read" on public.monthly_items;
create policy "monthly items read" on public.monthly_items for select to authenticated using (public.is_active_user());

create policy "active households read" on public.households for select to authenticated using (public.is_active_user());
create policy "admin registration requests read" on public.registration_requests for select to authenticated using (public.is_admin());

drop policy if exists "complaint images read" on storage.objects;
drop policy if exists "complaint images upload" on storage.objects;
create policy "complaint images read" on storage.objects for select to authenticated
  using (bucket_id = 'complaint-images' and public.is_active_user());
create policy "complaint images upload" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'complaint-images'
    and public.is_active_user()
    and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
  );

revoke all on public.households from anon;
revoke all on public.registration_requests from anon;
revoke all on public.resident_auth_attempts from anon, authenticated;
grant select on public.households to authenticated;
grant select on public.registration_requests to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select on public.households, public.profiles, public.registration_requests to service_role;
grant select, insert, delete on public.resident_auth_attempts to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.approve_registration(bigint) from public;
revoke all on function public.reject_registration(bigint) from public;
revoke all on function public.bootstrap_first_admin(integer, integer, text) from public;
grant execute on function public.approve_registration(bigint) to authenticated;
grant execute on function public.reject_registration(bigint) to authenticated;
