create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  phone text not null unique,
  building text not null,
  unit text not null,
  role text not null default 'resident' check (role in ('resident', 'admin')),
  approved boolean not null default false,
  created_at timestamptz not null default now(),
  unique (building, unit)
);

create table public.complaints (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  category text not null,
  location text not null,
  content text not null,
  status text not null default 'pending' check (status in ('pending', 'received', 'progress', 'complete')),
  priority text not null default 'normal' check (priority in ('normal', 'high')),
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.complaint_comments (
  id bigint generated by default as identity primary key,
  complaint_id bigint not null references public.complaints(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table public.complaint_history (
  id bigint generated by default as identity primary key,
  complaint_id bigint not null references public.complaints(id) on delete cascade,
  status text not null check (status in ('pending', 'received', 'progress', 'complete')),
  note text not null,
  created_at timestamptz not null default now()
);

create table public.notices (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  body text not null,
  pinned boolean not null default false,
  published_at date not null default current_date,
  author_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.monthly_records (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('fee', 'income')),
  month date not null,
  total numeric(14, 0) not null,
  previous numeric(14, 0) not null,
  unique (kind, month)
);

create table public.monthly_items (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.monthly_records(id) on delete cascade,
  name text not null,
  current_amount numeric(14, 0) not null,
  previous_amount numeric(14, 0) not null,
  sort_order integer not null default 0
);

create view public.profile_directory as
  select id, name, building, unit, role, approved, created_at from public.profiles where approved = true;
revoke all on public.profile_directory from anon;
grant select on public.profile_directory to authenticated;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin' and approved = true);
$$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, email, name, phone, building, unit)
  values(new.id, new.email, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'phone', new.raw_user_meta_data->>'building', new.raw_user_meta_data->>'unit');
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.protect_profile_privileges() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() and (new.role <> old.role or new.approved <> old.approved or new.id <> old.id) then raise exception '권한 필드는 변경할 수 없습니다.'; end if;
  return new;
end;
$$;
create trigger protect_profile_privileges before update on public.profiles for each row execute function public.protect_profile_privileges();

create or replace function public.touch_complaint() returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
create trigger touch_complaint before update on public.complaints for each row execute function public.touch_complaint();

create or replace function public.track_complaint_change() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.complaint_history(complaint_id, status, note) values(new.id, new.status, case when public.is_admin() then '관리사무소 민원 등록' else '입주민 민원 등록' end);
  elsif new.status <> old.status then
    insert into public.complaint_history(complaint_id, status, note) values(new.id, new.status, '관리자가 처리 상태를 변경');
  end if;
  return new;
end;
$$;
create trigger track_complaint_change after insert or update on public.complaints for each row execute function public.track_complaint_change();

alter table public.profiles enable row level security;
alter table public.complaints enable row level security;
alter table public.complaint_comments enable row level security;
alter table public.complaint_history enable row level security;
alter table public.notices enable row level security;
alter table public.monthly_records enable row level security;
alter table public.monthly_items enable row level security;

create policy "own or admin profiles read" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "own profile update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "admin profiles update" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "complaints read" on public.complaints for select to authenticated using (author_id = auth.uid() or public.is_admin());
create policy "complaints insert" on public.complaints for insert to authenticated with check ((author_id = auth.uid() and status = 'pending') or public.is_admin());
create policy "admin complaints update" on public.complaints for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "comments read" on public.complaint_comments for select to authenticated using (exists(select 1 from public.complaints c where c.id = complaint_id and (c.author_id = auth.uid() or public.is_admin())));
create policy "comments insert" on public.complaint_comments for insert to authenticated with check (user_id = auth.uid() and exists(select 1 from public.complaints c where c.id = complaint_id and (c.author_id = auth.uid() or public.is_admin())));
create policy "history read" on public.complaint_history for select to authenticated using (exists(select 1 from public.complaints c where c.id = complaint_id and (c.author_id = auth.uid() or public.is_admin())));
create policy "notices read" on public.notices for select to authenticated using (true);
create policy "admin notices insert" on public.notices for insert to authenticated with check (public.is_admin());
create policy "admin notices update" on public.notices for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin notices delete" on public.notices for delete to authenticated using (public.is_admin());
create policy "monthly records read" on public.monthly_records for select to authenticated using (true);
create policy "monthly items read" on public.monthly_items for select to authenticated using (true);
create policy "admin monthly records insert" on public.monthly_records for insert to authenticated with check (public.is_admin());
create policy "admin monthly records update" on public.monthly_records for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin monthly records delete" on public.monthly_records for delete to authenticated using (public.is_admin());
create policy "admin monthly items insert" on public.monthly_items for insert to authenticated with check (public.is_admin());
create policy "admin monthly items update" on public.monthly_items for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin monthly items delete" on public.monthly_items for delete to authenticated using (public.is_admin());

insert into storage.buckets(id, name, public) values('complaint-images', 'complaint-images', false) on conflict (id) do nothing;
create policy "complaint images read" on storage.objects for select to authenticated using (bucket_id = 'complaint-images');
create policy "complaint images upload" on storage.objects for insert to authenticated with check (bucket_id = 'complaint-images' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()));
