-- Preserve household residency changes and invalidate the household QR when
-- either the current resident or the current resident's move-in date changes.

create table public.household_residency_history (
  id bigint generated by default as identity primary key,
  household_id bigint not null references public.households(id) on delete cascade,
  event_type text not null check (event_type in ('move_in', 'resident_change', 'move_out', 'move_in_date')),
  previous_resident_id uuid references public.profiles(id) on delete set null,
  resident_id uuid references public.profiles(id) on delete set null,
  previous_move_in_date date,
  move_in_date date,
  changed_by uuid references public.admin_accounts(id) on delete set null,
  created_at timestamptz not null default now()
);

create index household_residency_history_household_idx
on public.household_residency_history(household_id, created_at desc, id desc);

create or replace function public.rotate_qr_for_residency_change(target_household_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.household_qr_codes
  set qr_code = gen_random_uuid(),
      rotated_by = case when public.is_admin() then auth.uid() else null end,
      rotated_at = now()
  where household_id = target_household_id;

  if not found then
    raise exception '세대 QR 정보를 찾을 수 없습니다.';
  end if;
end;
$$;

create or replace function public.track_household_resident_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_move_in_date date;
  new_move_in_date date;
begin
  if new.current_resident_id is not distinct from old.current_resident_id then
    return new;
  end if;

  select move_in_date into old_move_in_date
  from public.resident_cards
  where resident_id = old.current_resident_id;

  select move_in_date into new_move_in_date
  from public.resident_cards
  where resident_id = new.current_resident_id;

  insert into public.household_residency_history(
    household_id,
    event_type,
    previous_resident_id,
    resident_id,
    previous_move_in_date,
    move_in_date,
    changed_by
  ) values (
    new.id,
    case
      when old.current_resident_id is null then 'move_in'
      when new.current_resident_id is null then 'move_out'
      else 'resident_change'
    end,
    old.current_resident_id,
    new.current_resident_id,
    old_move_in_date,
    new_move_in_date,
    case when public.is_admin() then auth.uid() else null end
  );

  perform public.rotate_qr_for_residency_change(new.id);
  return new;
end;
$$;

create trigger track_household_resident_change
after update of current_resident_id on public.households
for each row execute function public.track_household_resident_change();

create or replace function public.track_resident_move_in_date()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_household_id bigint;
  previous_date date;
begin
  if tg_op = 'UPDATE' then
    previous_date := old.move_in_date;
  else
    previous_date := null;
  end if;

  if new.move_in_date is not distinct from previous_date then
    return new;
  end if;

  select h.id into target_household_id
  from public.households h
  join public.profiles p on p.household_id = h.id
  where p.id = new.resident_id
    and h.current_resident_id = new.resident_id;

  if target_household_id is null then
    return new;
  end if;

  insert into public.household_residency_history(
    household_id,
    event_type,
    previous_resident_id,
    resident_id,
    previous_move_in_date,
    move_in_date,
    changed_by
  ) values (
    target_household_id,
    'move_in_date',
    new.resident_id,
    new.resident_id,
    previous_date,
    new.move_in_date,
    case when public.is_admin() then auth.uid() else null end
  );

  perform public.rotate_qr_for_residency_change(target_household_id);
  return new;
end;
$$;

create trigger track_resident_move_in_date
after insert or update of move_in_date on public.resident_cards
for each row execute function public.track_resident_move_in_date();

alter table public.household_residency_history enable row level security;

create policy "admin household residency history read"
on public.household_residency_history for select to authenticated
using (public.is_admin());

revoke all on public.household_residency_history from anon, authenticated;
grant select on public.household_residency_history to authenticated;
grant usage, select on sequence public.household_residency_history_id_seq to authenticated;

revoke all on function public.rotate_qr_for_residency_change(bigint) from public;
revoke all on function public.track_household_resident_change() from public;
revoke all on function public.track_resident_move_in_date() from public;
