-- Record the initial publication and every administrator change to a notice.
-- Previous values remain visible only to administrators through RLS.

create table public.notice_history (
  id bigint generated by default as identity primary key,
  notice_id bigint not null references public.notices(id) on delete cascade,
  action text not null check (action in ('created', 'updated')),
  changed_by uuid references public.admin_accounts(id) on delete set null,
  changes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index notice_history_notice_idx
on public.notice_history(notice_id, created_at desc, id desc);

-- Give notices created before this migration a baseline history entry.
insert into public.notice_history(notice_id, action, changed_by, changes, created_at)
select n.id,
       'created',
       case when a.id is not null then n.author_id else null end,
       jsonb_build_object(
         'category', n.category,
         'title', n.title,
         'body', n.body,
         'pinned', n.pinned,
         'has_image', n.image_path is not null
       ),
       n.created_at
from public.notices n
left join public.admin_accounts a on a.id = n.author_id;

create or replace function public.track_notice_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  changed_fields jsonb := '{}'::jsonb;
begin
  if tg_op = 'INSERT' then
    insert into public.notice_history(notice_id, action, changed_by, changes)
    values (
      new.id,
      'created',
      auth.uid(),
      jsonb_build_object(
        'category', new.category,
        'title', new.title,
        'body', new.body,
        'pinned', new.pinned,
        'has_image', new.image_path is not null
      )
    );
  else
    if new.category is distinct from old.category then
      changed_fields := changed_fields || jsonb_build_object(
        'category', jsonb_build_object('before', old.category, 'after', new.category)
      );
    end if;
    if new.title is distinct from old.title then
      changed_fields := changed_fields || jsonb_build_object(
        'title', jsonb_build_object('before', old.title, 'after', new.title)
      );
    end if;
    if new.body is distinct from old.body then
      changed_fields := changed_fields || jsonb_build_object(
        'body', jsonb_build_object('before', old.body, 'after', new.body)
      );
    end if;
    if new.pinned is distinct from old.pinned then
      changed_fields := changed_fields || jsonb_build_object(
        'pinned', jsonb_build_object('before', old.pinned, 'after', new.pinned)
      );
    end if;
    if new.image_path is distinct from old.image_path then
      changed_fields := changed_fields || jsonb_build_object(
        'has_image', jsonb_build_object(
          'before', old.image_path is not null,
          'after', new.image_path is not null
        )
      );
    end if;

    if changed_fields <> '{}'::jsonb then
      insert into public.notice_history(notice_id, action, changed_by, changes)
      values (new.id, 'updated', auth.uid(), changed_fields);
    end if;
  end if;

  return new;
end;
$$;

create trigger track_notice_change
after insert or update of category, title, body, pinned, image_path on public.notices
for each row execute function public.track_notice_change();

alter table public.notice_history enable row level security;

create policy "admin notice history read"
on public.notice_history for select to authenticated
using (public.is_admin());

revoke all on public.notice_history from anon, authenticated;
grant select on public.notice_history to authenticated;
grant select, insert, update, delete on public.notice_history to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.track_notice_change() from public;

